modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
issueTrackerURL="https://github.com/liansishen/GTMThings/issues"
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
    modId = "gtmthings"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    authors="${mod_authors}"
    description = '''
Add some machines to GregTech-Modern
'''

    [[dependencies.gtmthings]]
        modId = "forge"
        mandatory = true
        versionRange = "[${forge_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.gtmthings]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[${minecraft_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.gtmthings]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[${gtceu_version},)"
        ordering = "AFTER"
        side = "BOTH"
    [[dependencies.gtmthings]]
        modId = "ae2"
        mandatory = true
        versionRange = "[${ae2_version},)"
        ordering = "AFTER"
        side = "BOTH"
